language: node_js

node_js:
  - "11"
  - "12"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run lint
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master